default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ror
  password: 12345

development:
  <<: *default
  database: stock_management_development

test:
  <<: *default
  database: stock_management_test

production:
  <<: *default
  database: stock_management_production
  username: ror
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
